
import React, { Component } from 'react';
import { AppRegistry, Text, View, StyleSheet, TouchableOpacity, Dimensions, Image } from 'react-native';
import Constants from 'expo-constants';

import { COLORS} from './COLORS';

let deviceHeight = Dimensions.get('window').height;
let deviceWidth = Dimensions.get('window').width;

//every style used (not much to talk about rly)
export default StyleSheet.create({
    container: {
        height: deviceHeight,
        width: deviceWidth,
        backgroundColor: COLORS.background1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    creditsContainer: {
        height: deviceHeight,
        width: deviceWidth,
        backgroundColor: COLORS.background1,
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    artContainer: {
        height: deviceHeight,
        width: deviceWidth,
        backgroundColor: COLORS.background1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    creditsText: {
        fontSize: deviceHeight/45,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    instructionsContainer: {
        height: deviceHeight,
        width: deviceWidth,
        backgroundColor: COLORS.background1,
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    explorationButtonSpacerRow: {
        height: deviceHeight/12,
        width: deviceWidth/2,
        flexDirection: 'row',
        marginTop: deviceHeight/20,
    },
    rowSpacer: {
        width: deviceWidth/10
    },
    rowSpacer2: {
        width: deviceWidth/20
    },
    rowSpacer3: {
        width: deviceWidth/5
    },
    rowSpacer4: {
        width: deviceWidth/2
    },
    explorationCaptureButton: {
        backgroundColor: 'rgba(0,184,0, 0.6)',
        height: deviceHeight/12,
        width: deviceWidth/2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    explorationEndCaptureButton: {
        backgroundColor: COLORS.assassin,
        height: deviceHeight/12,
        width: deviceWidth/2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    explorationCapturedButton: {
        backgroundColor: 'rgba(138, 1, 1, 0.6)',
        height: deviceHeight/12,
        width: deviceWidth/2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    explorationCaptureButton2: {
        backgroundColor: 'rgba(138, 1, 1, 0.5)',
        height: deviceHeight/12,
        width: deviceWidth/2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    explorationEndCaptureButton2: {
        backgroundColor: COLORS.knight,
        height: deviceHeight/12,
        width: deviceWidth/2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    explorationCapturedButton2: {
        backgroundColor: 'rgba(0,184,0, 0.6)',
        height: deviceHeight/12,
        width: deviceWidth/2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    BaseButtonTextBorder:{
        fontSize: deviceHeight/40,
        color: COLORS.background2,
        fontWeight: '600',
        textAlign: 'center',
        borderBottomColor: COLORS.background2,
        borderBottomWidth: deviceHeight/125,
    },
    BaseButtonText:{
        fontSize: deviceHeight/50,
        color: COLORS.background2,
        fontWeight: '900',
        textAlign: 'center',
    },
    smitheryContainer: {
        height: deviceHeight,
        width: deviceWidth,
        backgroundColor: COLORS.background1,
        justifyContent: 'align-evenly',
        alignItems: 'center',
        borderWidth: deviceWidth/30,
        borderColor: COLORS.background2,
    },
    converterContainer: {
        height: deviceHeight/1.05,
        width: deviceWidth,
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    imageContainer: {
        height: deviceHeight/2,
        width: deviceWidth/1.5,
        backgroundColor: COLORS.background2,
        borderWidth: deviceWidth/40,
        borderColor: COLORS.background1,
        borderRadius: deviceWidth/40,
        alignItems: 'center',
        justifyContent: 'center',
        opacity: .96,
    },
    statsContainer: {
        height: deviceHeight/4,
        width: deviceWidth/2,
        borderBottomColor: COLORS.background2,
        borderRightColor: COLORS.background2,
        borderRightWidth: deviceWidth/50,
        borderBottomWidth: deviceWidth/50,
        alignItems: 'flex-start',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'flex-start',
        position: 'relative',
        borderTopWidth: deviceWidth/100,
        borderTopColor: COLORS.background2,
        borderLeftWidth: deviceWidth/100,
        borderLeftColor: COLORS.background2,
        borderLeftEndRadius: deviceWidth/100
    },
    resourcesContainer: {
        height: deviceHeight/4,
        width: deviceWidth/2.15,
        borderBottomColor: COLORS.background2,
        borderBottomWidth: deviceWidth/50,
        alignItems: 'flex-start',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'flex-start',
        position: 'relative',
        borderTopWidth: deviceWidth/100,
        borderTopColor: COLORS.background2,
        borderTopEndRadius: deviceWidth/100,
        borderRightWidth: deviceWidth/100,
        borderRightColor: COLORS.background2,
        borderRightEndRadius: deviceWidth/100
    },
    statsText: {
        fontSize: deviceHeight/60,
        color: COLORS.background2,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
    },
    resourcesText: {
        fontSize: deviceHeight/50,
        color: COLORS.darkMatterMid,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
    },
    resourcesTextBorder: {
        borderBottomColor: COLORS.darkMatterMid,
        borderBottomWidth: deviceHeight/200,
        width: deviceWidth/2.19,
        padding: deviceHeight/200,
    },
    resourcesMainText: {
        fontSize: deviceHeight/50,
        color: COLORS.darkMatterBlue,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
        width: deviceWidth/2.13,
        marginTop: deviceHeight/200,

    },
    topKnightViewContainer: {
        height: deviceHeight/4,
        width: deviceWidth,
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'flex-start'
    },
    shopRowContainer: {
        height: deviceHeight/10,
        width: deviceWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly'
    },
    miniRowContainer: {
        height: deviceHeight/20,
        width: deviceWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly'
    },
    converterRow: {
        height: deviceHeight/20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    artIconRow: {
        width: deviceWidth,
        height: deviceHeight/10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    artCharRow: {
        width: deviceWidth,
        height: deviceHeight/3,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
    },
    artTextBorder: {
        borderBottomColor: COLORS.darkMatterBlue,
        borderBottomWidth: deviceHeight/150,
        width: deviceWidth/2.5,
    },
    artText: {
        fontSize: deviceHeight/50,
        color: COLORS.darkMatterBlue,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
    },
    artTextBorder2: {
        borderBottomColor: COLORS.darkMatterBlue,
        borderBottomWidth: deviceHeight/200,
        width: deviceWidth/2.5,
        marginTop: deviceHeight/40,
    },
    artText2: {
        fontSize: deviceHeight/60,
        color: COLORS.darkMatterBlue,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
    },
    converterText: {
        fontSize: deviceHeight/40,
        color: COLORS.darkMatterMid,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
    },
    converterPriceText: {
        color: COLORS.darkMatterDark,
        fontSize: deviceHeight/70,
        fontWeight: '900',
        textAlign: 'center',
    },
    converterPriceText2: {
        color: COLORS.darkMatterLight,
        fontSize: deviceHeight/70,
        fontWeight: '900',
        textAlign: 'center',
        marginBottom: deviceHeight/250,
        opacity: 1,
        width: deviceWidth/7,
    },
    converterPriceText3: {
        color: COLORS.darkMatterBlue,
        fontSize: deviceHeight/70,
        fontWeight: '900',
        textAlign: 'center',
        marginBottom: deviceHeight/250,
        opacity: 1,
        width: deviceWidth/7,
    },
    converterItemContainer: {
        height: deviceHeight/12,
        width: deviceWidth/7.5,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-end',
        opacity: 1,
    },
    smallMargin: {
        height: deviceHeight/40,
    },
    margin: {
        height: deviceHeight/20,
    },
    title: {
        fontSize: deviceHeight/20,
        color: COLORS.title,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    title2: {
        fontSize: deviceHeight/20,
        color: COLORS.background1,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    subTitle: {
        fontSize: deviceHeight/40,
        color: COLORS.title,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    mainText: {
        fontSize: deviceHeight/45,
        color: COLORS.title,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    smallSubText: {
        fontSize: deviceHeight/60,
        color: COLORS.background2,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
    },
    smallSubTextBorder: {
        borderBottomColor: COLORS.background2,
        borderBottomWidth: deviceHeight/100,
        width: deviceWidth/2.1,
    },
    statColorFiller: {
        height: deviceHeight/40,
        width: deviceWidth,
        backgroundColor: COLORS.background2,
    },
    instructionsText: {
        fontSize: deviceHeight/75,
        color: COLORS.title,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: deviceHeight/100,
        width: deviceWidth,
        marginTop: deviceHeight/80,
    },
    text: {
        fontSize: deviceHeight/60,
        color: 'black',
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,
    },
    knightText: {
        fontSize: deviceHeight/40,
        color: COLORS.knight,
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,  
    },
    assassinText: {
        fontSize: deviceHeight/40,
        color: COLORS.assassin,
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,  
    },
    knightTitle: {
        fontSize: deviceHeight/25,
        color: COLORS.knight,
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,  
    },
    buttonText: {
        color: COLORS.background1,
        fontSize: deviceHeight/30,
        fontWeight: 'bold',
    },
    shopButtonText: {
        color: COLORS.background2,
        fontSize: deviceHeight/80,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    priceText: {
        color: COLORS.darkMatterLight,
        fontSize: deviceHeight/100,
        fontWeight: '900',
        textAlign: 'center',
    },
    priceText2: {
        color: COLORS.background1,
        fontSize: deviceHeight/100,
        fontWeight: '900',
        textAlign: 'center',
    },
    priceTextBorder: {
        borderBottomColor: COLORS.darkMatterLight,
        borderBottomWidth: deviceHeight/350,
        width: deviceWidth/3.35,
        alignItems: 'center',
        justifyContent: 'center',
    },
    smitherySubText: {
        fontSize: deviceHeight/40,
        color: COLORS.knight,
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,  
    },
    armorySubText: {
        fontSize: deviceHeight/40,
        color: COLORS.assassin,
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,  
    },
    armorySubTextBorder: {
        borderBottomColor: COLORS.assassin,
        borderBottomWidth: deviceHeight/100,
        width: deviceWidth/3,
    },
    smitherySubTextBorder: {
        borderBottomColor: COLORS.knight,
        borderBottomWidth: deviceHeight/100,
        width: deviceWidth/3,
    },
    converterSubText: {
        fontSize: deviceHeight/40,
        color: COLORS.darkMatterMid,
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,  
        width: deviceWidth/2.6,
    },
    border1: {
        opacity: 1.0,  
        borderBottomColor: COLORS.darkMatterMid,
        borderBottomWidth: deviceHeight/100,
        width: deviceWidth/2.6,
    },
    border2: {
        borderBottomColor: COLORS.darkMatterDark,
        borderBottomWidth: deviceHeight/350,
        marginBottom: deviceHeight/250,
        opacity: 1,
        width: deviceWidth/7,
    },
    border2v2: {
        borderBottomColor: COLORS.darkMatterLight,
        borderBottomWidth: deviceHeight/350,
        marginBottom: deviceHeight/250,
        opacity: 1,
        width: deviceWidth/7,
    },
    border2v3: {
        borderBottomColor: COLORS.darkMatterBlue,
        borderBottomWidth: deviceHeight/350,
        marginBottom: deviceHeight/250,
        opacity: 1,
        width: deviceWidth/7,
    },
    caption: {
        marginTop: deviceHeight/40,
        height: deviceHeight/8,
        width: deviceWidth/1.1,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: deviceWidth/50,
        borderColor: COLORS.background2,
        borderRadius: deviceWidth/20,
    },
    captionInt: {
        height: deviceHeight/8,
        width: deviceWidth/1.1,
        backgroundColor: 'rgba(61, 67, 61, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: deviceWidth/20,
        borderWidth: deviceWidth/50,
        borderColor: COLORS.background1,
    },
    textInput: {
        borderBottomColor: 'rgba(96, 181, 96, 0.6)',
        borderBottomWidth: deviceHeight/80,
        height: deviceHeight/20,
        width: deviceWidth/2,
        opacity: 1,
        color: COLORS.title,
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        fontSize: deviceHeight/40,
        fontWeight: 'bold',
    },
    knightSelect: {
        height: deviceHeight/4,
        width: deviceWidth/2,
        borderWidth: deviceWidth/50,
        borderRadius: deviceWidth/20,
        borderColor: COLORS.background2,
        backgroundColor: COLORS.knight,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: deviceHeight/16,
    },
    knightContainer: {
        height: deviceHeight,
        width: deviceWidth,
        backgroundColor: COLORS.knight,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: deviceWidth/50,
        borderRadius: deviceWidth/20,
        borderColor: COLORS.background2,
    },
    knightMainContainer: {
        height: deviceHeight,
        width: deviceWidth,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        borderWidth: deviceWidth/50,
        borderRadius: deviceWidth/20,
        borderColor: COLORS.background2,
    },
    assassinSelect: {
        height: deviceHeight/4,
        width: deviceWidth/2,
        borderWidth: deviceWidth/50,
        borderRadius: deviceWidth/20,
        borderColor: COLORS.background2,
        backgroundColor: COLORS.assassin,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: deviceHeight/16,
    },
    assassinContainer: {
        height: deviceHeight,
        width: deviceWidth,
        backgroundColor: COLORS.assassin,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: deviceWidth/50,
        borderRadius: deviceWidth/20,
        borderColor: COLORS.background3,
    },
    assassinText: {
        fontSize: deviceHeight/40,
        color: COLORS.assassin,
        fontWeight: '900',
        textAlign: 'center',
        opacity: 1.0,  
    },
    bigButton: {
        backgroundColor: COLORS.title,
        height: deviceHeight/8,
        width: deviceWidth/3,
        alignItems: 'center',
        justifyContent: 'center',
        borderStartColor: COLORS.background2,
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    buttonLng: {
        backgroundColor: COLORS.background2,
        height: deviceHeight/10,
        width: deviceWidth/2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderRadius: deviceWidth/30,
    },
    ConversionBtn: {
        height: deviceHeight/10,
        width: deviceWidth/2.25,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        borderColor: COLORS.darkMatterMid,
        borderWidth: deviceWidth/80,
        borderRadius: deviceWidth/30,
    },
    ConversionBtn2: {
        height: deviceHeight/10,
        width: deviceWidth/2.25,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        borderColor: COLORS.darkMatterLight,
        borderWidth: deviceWidth/80,
        borderRadius: deviceWidth/30,
    },
    ConversionBtn3: {
        height: deviceHeight/10,
        width: deviceWidth/2.25,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        borderColor: COLORS.darkMatterBlue,
        borderWidth: deviceWidth/80,
        borderRadius: deviceWidth/30,
    },
    shopButton: {
        backgroundColor: COLORS.knight,
        height: deviceHeight/12,
        width: deviceWidth/3,
        alignItems: 'center',
        justifyContent: 'align-evenly',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    shopButton2: {
        backgroundColor: COLORS.assassin,
        height: deviceHeight/12,
        width: deviceWidth/3,
        alignItems: 'center',
        justifyContent: 'align-evenly',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
    },
    selectionText: {
        fontSize: deviceHeight/30,
        color: COLORS.background2,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    dmButton: {
        backgroundColor: COLORS.darkMatterMid,
        height: deviceHeight/8,
        width: deviceWidth/1.3,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: deviceWidth/60,
        borderCurve: 'circular',
        borderRadius: deviceWidth/30, 
        flexDirection: 'row',
        marginLeft: deviceWidth/10,
        marginTop: deviceHeight/6.5,
    },
    dmText: {
        fontSize: deviceHeight/50,
        color: COLORS.darkMatterBlue,
        fontWeight: '600',
        textAlign: 'center',
        opacity: 1.0,
    },
});